#!/usr/bin/env bash
# Redirection
#nginx -t -c /etc/nginx/nginx.conf - check sintax configuration file
#sudo service nginx restart - do always after make changes in the server
sudo apt update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
redirection="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/# as directory, then fall back to displaying a 404./a $redirection" /etc/nginx/sites-available/default
sudo service nginx restart
