#!/usr/bin/env bash
# Redirection
redirection="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/# First attempt to serve request as file, then/ a\\$redirection" /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx reload
