#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
sudo apt update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
echo "Ceci n'est pas une page" > error.html
sudo mv error.html /var/www/html/
redirection="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/# as directory, then fall back to displaying a 404./a $redirection" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a error_page 404 /error.html;" /etc/nginx/sites-available/default
sudo service nginx restart
