#!/usr/bin/env bash
#install your load balancer
sudo apt update
sudo apt-get -y install haproxy
sudo echo -e "listen firstbalance\n\tbind *:80\n\toption forwardfor\n\toption httpchk\n\tbalance roundrobin\n\tserver 4765-web-01 54.235.14.170:80 check\n\tserver 4765-web-02 54.83.58.3:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
