#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while ((i<21))
do
    if [ $i -eq 4 ]
        then
            echo "$i"
            echo "bad luck from China"
    elif [ $i -eq 9 ]
        then
            echo "$i"
            echo "bad luck from Japan luck"
    elif [ $i -eq 17 ]
        then
            echo "$i"
            echo "bad luck from Italy"
    else
        echo "$i"
    fi
    i=$((i + 1))
done