#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
read -r number
i=1
while ((i<=number))
do
    echo "$i"
    case $i in
    4)
        echo "bad luck from China"
    ;;
    9)
        echo "bad luck from Japan"
    ;;
    17)
        echo "bad luck from Italy"
    ;;
    esac
    ((i++))
done