#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
j=1
while ((i<=12))
do
    echo "Hour: $i"
    while ((j<=59))
    do
        echo "$j"
        ((j++))
    done
    ((i++))
    j=1
done