#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
if [ -e "school" ]
    then
        echo "school file exists"
        if [ -s "school" ]
        then
            echo "File not empty"
        else 
            echo "File empty"
        fi               
        if [ -f "school" ]
        then
            echo "school is a regular file"
        fi
else
    echo "school file does not exist"
fi
