#!/usr/bin/env bash
#Block all incoming traffic but
#Configure ufw so that it blocks all incoming traffic, except the following TCP ports:
#22 (SSH)
#443 (HTTPS SSL)
#80 (HTTP)
sudo apt-get update
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
